spring.application.name=enterprise-ai-agent

####################################################
# AI Model
####################################################

spring.ai.model.chat=google-genai
spring.ai.model.embedding=ollama

####################################################
# Gemini
####################################################

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=your-gcp-project-id
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.chat.model=gemini-2.5-flash

server.port=8082

####################################################
# Enterprise AI Assistant
####################################################

enterprise.assistant.base-url=http://localhost:8080
enterprise.assistant.login-url=/api/auth/login
enterprise.assistant.chat-url=/api/rag/chat

enterprise.assistant.username=admin
enterprise.assistant.password=admin123